# Generated by Django 3.2.7 on 2021-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=13)),
                ('Location', models.CharField(max_length=255)),
                ('Parking_Slot', models.CharField(max_length=255)),
                ('Parking_Date', models.DateTimeField()),
            ],
        ),
    ]
